version: "2.29.1"

services:
  backend:
    build:
      context: ./backend
    container_name: backend_c
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
    container_name: frontend_c
    volumes:
      - ./frontend:/scr
      - ./frontend:/node_modules
    ports:
      - "3000:3000"